### PR TITLE
Fix boltzmann authneeded response; Make local NODE_ENV consistent

### LINKED ISSUE #127: Failed to login on new instance
Got 

```
registry_1  | ⚠️ Response from registry/handlers/* > 500ms fetching "GET /www/login/providers/github/callback?code=2903b914d5428f6e950c&state=0.6057451335630384".
registry_1  |  - (Tune timeout using DEV_LATENCY_WARNING_MS env variable.)
registry_1  | error: database "entropic_development" does not exist
registry_1  |     at Connection.parseE (/services/registry/node_modules/pg/lib/connection.js:553:11)
registry_1  |     at Connection.parseMessage (/services/registry/node_modules/pg/lib/connection.js:378:19)
registry_1  |     at Socket.<anonymous> (/services/registry/node_modules/pg/lib/connection.js:119:22)
registry_1  |     at Socket.emit (events.js:200:13)
registry_1  |     at addChunk (_stream_readable.js:290:12)
registry_1  |     at readableAddChunk (_stream_readable.js:271:11)
registry_1  |     at Socket.Readable.push (_stream_readable.js:226:10)
registry_1  |     at TCP.onStreamRead (internal/stream_base_commons.js:166:17)
registry_1  | From previous event:
registry_1  |     at materialize (/services/registry/node_modules/ormnomnom/lib/queryset.js:404:19)
registry_1  |     at QuerySet.createStream (/services/registry/node_modules/ormnomnom/lib/queryset.js:233:5)
registry_1  |     at /services/registry/node_modules/ormnomnom/lib/queryset.js:261:24
registry_1  | From previous event:
registry_1  |     at QuerySet.then (/services/registry/node_modules/ormnomnom/lib/queryset.js:260:12)
registry_1  |     at QuerySet.get (/services/registry/node_modules/ormnomnom/lib/queryset.js:115:43)
registry_1  |     at DAO.proto.get (/services/registry/node_modules/ormnomnom/lib/ormnomnom.js:66:29)
registry_1  |     at oauthCallback (/services/registry/handlers/www.js:97:6)
registry_1  |     at processTicksAndRejections (internal/process/task_queues.js:89:5)
registry_1  |     at async inner (/services/common/boltzmann/middleware/dev-only.js:45:16)
registry_1  |     at async inner (/services/common/boltzmann/middleware/dev-only.js:45:16) {
registry_1  |   name: 'error',
registry_1  |   length: 105,
registry_1  |   severity: 'FATAL',
registry_1  |   code: '3D000',
redis_1     | 1:C 03 Jun 2019 21:
```

However, the .env file has `entropic_dev` as the database name and when I grep the code base for `entropic_development` there's nothing there.

However when i changed `NODE_ENV` to `dev` from the default of `development` everything was kosher.

I think this has something to do with:

```
registry_1  | > entropic-registry@0.0.1 migrate /services/registry
registry_1  | > PGUSER=postgres PGDATABASE=entropic_${NODE_ENV:-dev} db-migrate up --config db-migrate.json --env entropic
```

I'm gonna try to take a quick look at that tonight

### LINKED ISSUE #129: Registry responds with 200 when token is invalid
Example request and response:

```
> GET /v1/auth/whoami HTTP/1.1
> Host: registry.entropic.dev
> User-Agent: insomnia/6.5.4
> Authorization: Bearer fake
> Accept: */*

< HTTP/1.1 200 OK
< Server: nginx/1.14.0 (Ubuntu)
< Date: Mon, 03 Jun 2019 20:55:59 GMT
< Content-Type: text/plain;charset=UTF-8
< Content-Length: 58
< Connection: keep-alive
< Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
< X-Frame-Options: sameorigin
< X-Clacks-Overhead: GNU/Terry Pratchett

{"error":"Your auth token is not a valid entropic token."}
```

### PR DESCRIPTION
**Pull request by gribnoysup**
Spotted a few things while working on #118 

- `status` and `headers` were passed to `Response` constructor as separate arguments. Should be a `ResponseInit` object instead. Because of that currently https://registry.entropic.dev/v1/auth/whoami returns 200 when `authneeded`. Closes #129
- Different NODE_ENVs (`dev` and `development`) in start scripts for local environment were causing issues when I was trying to run the registry thing locally. As [the docs suggest](https://github.com/entropic-dev/entropic/blob/master/services/registry/README.md#running-your-own-registry) that there are only three envs supported at the moment, I switched `dev` to `development`. Closes #127

### CODE REVIEW

**Comment by toddself** [comment]
LOL I just ran into and sorted out the `development` thing in #127

**Comment by gribnoysup** [comment]
Things in this repo are happening really fast 🤣

File: services/common/boltzmann/response.js [hunk 1]
```diff
@@ -88,6 +88,6 @@ function authneeded(message, status = 401, extraHeaders = {}) {
   if (typeof message === 'string') {
     message = { error: message };
   }
-  const r = new Response(JSON.stringify(message), status, headers);
+  const r = new Response(JSON.stringify(message), { status, headers });
```
Comment (chrisdickinson) [inline services/common/boltzmann/response.js]: Well hey, that's a great catch. :clap:

File: services/registry/package.json [hunk 2]
```diff
@@ -64,15 +64,15 @@
   },
   "scripts": {
     "coverage": "NODE_ENV=test PGUSER=postgres PGDATABASE=entropic_test nyc mocha -R spec",
-    "createdb": "createdbjs -h $PGHOST -U postgres entropic_${NODE_ENV:-dev} || true",
-    "dev": "NODE_ENV=dev PGUSER=postgres PGDATABASE=entropic_${NODE_ENV:-dev} ./server.js",
+    "createdb": "createdbjs -h $PGHOST -U postgres entropic_${NODE_ENV:-development} || true",
+    "dev": "NODE_ENV=development PGUSER=postgres PGDATABASE=entropic_${NODE_ENV:-development} ./server.js",
```
Comment (chrisdickinson) [inline services/registry/package.json]: Would you mind if we default to `dev`? The postgres database on entropic is set up for that one already.

**Comment by gribnoysup** [comment]
@chrisdickinson I made the changes and force pushed so the commits make a little bit more sense, should be ready to go
